#!/bin/sh
# Script to build the application and copy files into ${top_srcdir}/bin
# @web: http://sf.net/projects/gtkworkbook
# @author: jb <jvb4@njit.edu>

package="gtkworkbook"
top_dir=`pwd`
src_dir="$top_dir/src"
bin_dir="$top_dir/bin"

if [ ! -f configure ]; then
    echo "Regenerating project files..."
    sh autogen.sh
fi

if [ ! -f Makefile ]; then
    echo "Reconfiguring project with GNU autotools..."
    sh configure
fi

# create the directory if it does not exist
if [ ! -d $bin_dir ]; then
    echo "Creating $bin_dir..."
    mkdir $bin_dir
fi

make $@ || {
    echo " build failed"
    exit 1
}

# copy files into the directory for binaries
cp ${src_dir}/OBJS/pa1 ${bin_dir}/pa1

echo "Build of $package is complete; project file resides in $bin_dir"
