#!/bin/sh
# Script to build the application and copy files into ${top_srcdir}/bin
# @web: http://sf.net/projects/gtkworkbook
# @author: jb <jvb4@njit.edu>

package="gtkworkbook"
top_dir=`pwd`
bin_dir="$top_dir/bin"
cfg_dir="$top_dir/cfg"
lib_dir="$top_dir/lib/.libs"

if [ ! -f configure ]; then
    echo "Regenerating project files..."
    sh autogen.sh
fi

if [ ! -f Makefile ]; then
    echo "Reconfiguring project with GNU autotools..."
    sh configure
fi

if [ ! -d $lib_dir ]; then
    echo "Creating $lib_dir..."
    mkdir -p $lib_dir
fi

if [ ! -d $bin_dir ]; then
    echo "Creating $bin_dir..."
    mkdir -p $bin_dir
fi

make $@ || {
    echo " build failed"
    exit 1
}

if [ ! -f ${cfg_dir}/application.cfg ]; then
    cp ${cfg_dir}/application.cfg ${bin_dir}/application.cfg
fi

cp ${lib_dir}/gtkworkbook ${bin_dir}/gtkworkbook
cp ${lib_dir}/largefile.so ${bin_dir}/largefile.so
cp ${lib_dir}/realtime.so ${bin_dir}/realtime.so
echo "Build of $package is complete."
echo "Project files resides in $bin_dir"
